# Generated by Django 5.1.1 on 2025-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(default=None, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
